### ISSUE TITLE
[FEATURE] Specify size of frame

### ISSUE THREAD

**Issue by navarr** [Th3C0D3R/GeForceNowWindowMover#6]
Hi!  I'm a streamer and I use a very large monitor.  I like to have my game running at 1920x1080 in a window.  I'm currently trying out GeForce NOW and the fullscreen thing is awful for me, as I surround my game window with chat, redeems, etc.

My feature request would be the ability to specify the size of the frame (e.g. 1920x1080) instead of eyeballing it.  As a CLI flag would be perfectly fine - then I could just focus on positioning it.

**Comment by Th3C0D3R** [comment]
@navarr
sorry for late response. do you want to use the wrapped form or the "fixed" borderless methode?
I assume the later one. Will update as soon as done

**Comment by Th3C0D3R** [comment]
implemented in this version https://github.com/Th3C0D3R/GeForceNowWindowMover/releases/tag/v0.0.21

**Comment by navarr** [comment]
It works perfectly, thank you!
